In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings('ignore')

In [2]:
url = "https://traveltriangle.com/tour-packages/kerala"
response = requests.get(url)
response

In [3]:
pagecontent = response.text

In [4]:
soup = BeautifulSoup(pagecontent)

In [6]:
name = soup.find("span",attrs={"class":"fw9 m0 f16 pfc3"})
name

In [14]:
names = []

for x in soup.find_all("span",attrs={"class":"fw9 m0 f16 pfc3"}):
    names.append(x.text.strip() if x else np.nan)

for name in names:
    print(name)

Alleppey-Munnar Kerala Weekend Tour
Charismatic Kochi Tour Package
Hills & Houseboat: Munnar and Alleppey Honeymoon Package
Vibrant Kochi Munnar Honeymoon Tour Package
Mesmerizing Getaway To Kochi
Kerala Wayanad Weekend Holiday
Trip To Mesmerising Munnar
Best Selling Kerala Honeymoon Tour Package
Catch The Beauty Of The Setting Sun In Alleppey
Best Selling Kerala Houseboat & Jungle Safari Tour Package
Charming Alleppey Honeymoon Package
A Blissful Tour In Munnar
Top 5 Nights 6 Days Kerala Family Tour Packages For A Refreshing Getaway
Exploring Godâs Own Country, Kerala
Reasonable Munnar Thekkady Alleppey Honeymoon Packages
Ecstatic Athirapally Tour Package
Mesmerizing Kerala Holiday: Weekend in Munnar & Thekkady
Captivating Thekkady Honeymoon Package
A Surreal Escape To Mesmerising Destinations
Visit Kerala And See Astounding Places

In [15]:
dp = soup.find("span",attrs = {"class":"f12 fw4 pt2 pb2 pl8 pr8 radius20 pbc1 sfcw at_discount_label"})
dp

In [16]:
dp = []

for x in soup.find_all("span",attrs={"class":"f12 fw4 pt2 pb2 pl8 pr8 radius20 pbc1 sfcw at_discount_label"}):
    dp.append(x.text.strip() if x else np.nan)

for name in dp:
    print(name)

24% Off
9% Off
10% Off
10% Off
9% Off
5% Off
9% Off
28% Off
9% Off
19% Off
9% Off
9% Off
18% Off
10% Off
12% Off
9% Off
29% Off
10% Off
21% Off
11% Off

In [17]:
cities = soup.find("ul",attrs = {"class":"clearfix package-cities-list at_packagecity_list"})
cities

In [20]:
cities = []

for x in soup.find_all("ul",attrs={"class":"clearfix package-cities-list at_packagecity_list"}):
    cities.append(x.text.strip() if x else np.nan)

for name in cities:
    print(name)

Munnar (2D)Alleppey (2D)
Kochi (1D)Munnar (3D)
Munnar (2D)Thekkady (1D)Alleppey (1D)Kochi (2D)
Cochin (1D)Munnar (3D)
Kochi (2D)
Wayanad (3D)
Munnar (2D)Alleppey (2D)
Munnar (2D)Thekkady (1D)Alleppey (2D)
Alleppey (2D)
Munnar (2D)Thekkady (1D)Alleppey (2D)
Alleppey (3D)
Munnar (3D)
Munnar (2D)Thekkady (1D)Alleppey (1D)Kochi (2D)
Munnar (1D)Alleppey (2D)
Munnar (1D)Thekkady (1D)Alleppey (2D)
Athirapally (2D)Munnar (2D)Alleppey (1D)Kovalam (1D)Trivandrum (2D)
Munnar (2D)Thekkady (2D)
Kumarakom (1D)Thekkady (1D)Munnar (3D)
Munnar (2D)Alleppey (2D)
Munnar (1D)Thekkady (1D)Kochi (2D)

In [21]:
for i in range(1,62):
    url = f"https://traveltriangle.com/tour-packages/Kerala/page/{i}"
    print(url)

https://traveltriangle.com/tour-packages/Kerala/page/1
https://traveltriangle.com/tour-packages/Kerala/page/2
https://traveltriangle.com/tour-packages/Kerala/page/3
https://traveltriangle.com/tour-packages/Kerala/page/4
https://traveltriangle.com/tour-packages/Kerala/page/5
https://traveltriangle.com/tour-packages/Kerala/page/6
https://traveltriangle.com/tour-packages/Kerala/page/7
https://traveltriangle.com/tour-packages/Kerala/page/8
https://traveltriangle.com/tour-packages/Kerala/page/9
https://traveltriangle.com/tour-packages/Kerala/page/10
https://traveltriangle.com/tour-packages/Kerala/page/11
https://traveltriangle.com/tour-packages/Kerala/page/12
https://traveltriangle.com/tour-packages/Kerala/page/13
https://traveltriangle.com/tour-packages/Kerala/page/14
https://traveltriangle.com/tour-packages/Kerala/page/15
https://traveltriangle.com/tour-packages/Kerala/page/16
https://traveltriangle.com/tour-packages/Kerala/page/17
https://traveltriangle.com/tour-packages/Kerala/page/18
https://traveltriangle.com/tour-packages/Kerala/page/19
https://traveltriangle.com/tour-packages/Kerala/page/20
https://traveltriangle.com/tour-packages/Kerala/page/21
https://traveltriangle.com/tour-packages/Kerala/page/22
https://traveltriangle.com/tour-packages/Kerala/page/23
https://traveltriangle.com/tour-packages/Kerala/page/24
https://traveltriangle.com/tour-packages/Kerala/page/25
https://traveltriangle.com/tour-packages/Kerala/page/26
https://traveltriangle.com/tour-packages/Kerala/page/27
https://traveltriangle.com/tour-packages/Kerala/page/28
https://traveltriangle.com/tour-packages/Kerala/page/29
https://traveltriangle.com/tour-packages/Kerala/page/30
https://traveltriangle.com/tour-packages/Kerala/page/31
https://traveltriangle.com/tour-packages/Kerala/page/32
https://traveltriangle.com/tour-packages/Kerala/page/33
https://traveltriangle.com/tour-packages/Kerala/page/34
https://traveltriangle.com/tour-packages/Kerala/page/35
https://traveltriangle.com/tour-packages/Kerala/page/36
https://traveltriangle.com/tour-packages/Kerala/page/37
https://traveltriangle.com/tour-packages/Kerala/page/38
https://traveltriangle.com/tour-packages/Kerala/page/39
https://traveltriangle.com/tour-packages/Kerala/page/40
https://traveltriangle.com/tour-packages/Kerala/page/41
https://traveltriangle.com/tour-packages/Kerala/page/42
https://traveltriangle.com/tour-packages/Kerala/page/43
https://traveltriangle.com/tour-packages/Kerala/page/44
https://traveltriangle.com/tour-packages/Kerala/page/45
https://traveltriangle.com/tour-packages/Kerala/page/46
https://traveltriangle.com/tour-packages/Kerala/page/47
https://traveltriangle.com/tour-packages/Kerala/page/48
https://traveltriangle.com/tour-packages/Kerala/page/49
https://traveltriangle.com/tour-packages/Kerala/page/50
https://traveltriangle.com/tour-packages/Kerala/page/51
https://traveltriangle.com/tour-packages/Kerala/page/52
https://traveltriangle.com/tour-packages/Kerala/page/53
https://traveltriangle.com/tour-packages/Kerala/page/54
https://traveltriangle.com/tour-packages/Kerala/page/55
https://traveltriangle.com/tour-packages/Kerala/page/56
https://traveltriangle.com/tour-packages/Kerala/page/57
https://traveltriangle.com/tour-packages/Kerala/page/58
https://traveltriangle.com/tour-packages/Kerala/page/59
https://traveltriangle.com/tour-packages/Kerala/page/60
https://traveltriangle.com/tour-packages/Kerala/page/61

In [22]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

Name = [] 

stay = []

location = []

discount = []

pagenum = []

Packages = []

Price = []
total_time = time.time()
for i in range(1, 62): 

    start_time = time.time()

    URL = f"https://traveltriangle.com/tour-packages/kerala?travelmonth=May%2C%202026={i}"

    page = requests.get(URL)

    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', attrs={'class':'col-12 p8 pt0'}):

        name_tag = x.find('p', attrs={"class":"col-md-12 pl0 fw9 m0 f16 pfc3 at_packageName"})

        stay_tag = x.find('span', attrs={'class':'iblock sfc6'})   # discounted price

        location_tag = x.find('ul', attrs={'class':'clearfix package-cities-list at_packagecity_list'})

        discount_tag = x.find('span', attrs={'class':'f12 fw4 pt2 pb2 pl8 pr8 radius20 pbc1 sfcw at_discount_label'})

        Price_tag = x.find('p', attrs={'class':'sfc3 m0 f20 fw9 priceVal at_newprice'})

        Tags_tag = x.find('ul',attrs={'class':'package-tags at_package_tags'})

        Name.append(name_tag.text.strip() if name_tag else np.nan)

        stay.append(stay_tag.text.strip() if stay_tag else np.nan)

        location.append(location_tag.text.strip() if location_tag else np.nan)

        discount.append(discount_tag.text.strip() if discount_tag else np.nan)

        Price.append(Price_tag.text.strip() if Price_tag else np.nan)

        Packages.append(Tags_tag.text.strip() if Tags_tag else np.nan)

        pagenum.append(i)
 
    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 2.43 seconds
Page 2 completed in 1.87 seconds
Page 3 completed in 1.97 seconds
Page 4 completed in 2.97 seconds
Page 5 completed in 1.85 seconds
Page 6 completed in 5.24 seconds
Page 7 completed in 1.85 seconds
Page 8 completed in 1.83 seconds
Page 9 completed in 2.06 seconds
Page 10 completed in 1.86 seconds
Page 11 completed in 1.88 seconds
Page 12 completed in 1.90 seconds
Page 13 completed in 1.79 seconds
Page 14 completed in 2.01 seconds
Page 15 completed in 1.94 seconds
Page 16 completed in 1.79 seconds
Page 17 completed in 1.75 seconds
Page 18 completed in 1.76 seconds
Page 19 completed in 1.94 seconds
Page 20 completed in 1.96 seconds
Page 21 completed in 1.82 seconds
Page 22 completed in 1.78 seconds
Page 23 completed in 1.99 seconds
Page 24 completed in 1.86 seconds
Page 25 completed in 1.91 seconds
Page 26 completed in 1.86 seconds
Page 27 completed in 1.88 seconds
Page 28 completed in 2.25 seconds
Page 29 completed in 1.87 seconds
Page 30 completed in 1.85 seconds
Page 31 completed in 2.00 seconds
Page 32 completed in 1.79 seconds
Page 33 completed in 2.64 seconds
Page 34 completed in 1.83 seconds
Page 35 completed in 1.82 seconds
Page 36 completed in 1.80 seconds
Page 37 completed in 1.85 seconds
Page 38 completed in 1.92 seconds
Page 39 completed in 1.86 seconds
Page 40 completed in 1.84 seconds
Page 41 completed in 1.87 seconds
Page 42 completed in 1.93 seconds
Page 43 completed in 3.67 seconds
Page 44 completed in 1.86 seconds
Page 45 completed in 1.78 seconds
Page 46 completed in 1.92 seconds
Page 47 completed in 1.85 seconds
Page 48 completed in 1.94 seconds
Page 49 completed in 1.88 seconds
Page 50 completed in 1.88 seconds
Page 51 completed in 1.84 seconds
Page 52 completed in 1.82 seconds
Page 53 completed in 1.98 seconds
Page 54 completed in 1.84 seconds
Page 55 completed in 1.79 seconds
Page 56 completed in 1.93 seconds
Page 57 completed in 1.90 seconds
Page 58 completed in 2.07 seconds
Page 59 completed in 1.83 seconds
Page 60 completed in 1.82 seconds
Page 61 completed in 1.80 seconds
Total Time Completed in seconds 122.2898018360138

In [23]:
df = pd.DataFrame({
    "Name": Name,
    "Stay": stay,
    "Location": location,
    "Discount": discount,
    "Price": Price,
    "Packages": Packages,
    "Page Number": pagenum})

In [24]:
df

,Name,Stay,Location,Discount,Price,Packages,Page Number
0,Alleppey-Munnar Kerala Weekend Tour,4 Days & 3 Nights,Munnar (2D)Alleppey (2D),24% Off,"â¹ 13,020/-â¹ 17,132/-",Spice PlantationsHill stationHouseboat StayCru...,1
1,Charismatic Kochi Tour Package,4 Days & 3 Nights,Kochi (1D)Munnar (3D),9% Off,"â¹ 15,000/-â¹ 16,484/-",WaterfallsAdventureNatureShoppingWildlifeCultu...,1
2,Hills & Houseboat: Munnar and Alleppey Honeymo...,6 Days & 5 Nights,Munnar (2D)Thekkady (1D)Alleppey (1D)Kochi (2D),10% Off,"â¹ 22,000/-â¹ 24,444/-",Periyar Wildlife SanctuaryCruisesEravikulam Na...,1
3,Vibrant Kochi Munnar Honeymoon Tour Package,4 Days & 3 Nights,Cochin (1D)Munnar (3D),10% Off,"â¹ 14,571/-â¹ 16,190/-",Scenic viewsAdventureTea gardensHill stationMa...,1
4,Mesmerizing Getaway To Kochi,2 Days & 1 Nights,Kochi (2D),9% Off,"â¹ 4,800/-â¹ 5,275/-",ScenerylandscapeSightseeingLeisure TimeNatureA...,1
...,...,...,...,...,...,...,...
1215,Ecstatic Athirapally Tour Package,8 Days & 7 Nights,Athirapally (2D)Munnar (2D)Alleppey (1D)Kovala...,9% Off,"â¹ 28,123/-â¹ 30,904/-",Athirapally waterfallsNatureMunnarHill station...,61
1216,Mesmerizing Kerala Holiday: Weekend in Munnar ...,4 Days & 3 Nights,Munnar (2D)Thekkady (2D),29% Off,"â¹ 13,167/-â¹ 18,434/-",HillsAdventureJungle SafariNatureWildlifeWeeke...,61
1217,Captivating Thekkady Honeymoon Package,5 Days & 4 Nights,Kumarakom (1D)Thekkady (1D)Munnar (3D),10% Off,"â¹ 15,624/-â¹ 17,360/-",Ideal for CouplesWater ActivitiesAdventureHous...,61
1218,A Surreal Escape To Mesmerising Destinations,4 Days & 3 Nights,Munnar (2D)Alleppey (2D),21% Off,"â¹ 12,880/-â¹ 16,269/-",RomanticHill stationHillsCruisesWaterfallsAdve...,61
1219,Visit Kerala And See Astounding Places,4 Days & 3 Nights,Munnar (1D)Thekkady (1D)Kochi (2D),11% Off,"â¹ 11,760/-â¹ 13,213/-",Natural BeautyTea GardenSpice GardenSightseein...,61

In [25]:
df.to_csv("travel.csv",index = False)

In [26]:
df = pd.read_csv("travel.csv")
df

,Name,Stay,Location,Discount,Price,Packages,Page Number
0,Alleppey-Munnar Kerala Weekend Tour,4 Days & 3 Nights,Munnar (2D)Alleppey (2D),24% Off,"â¹ 13,020/-â¹ 17,132/-",Spice PlantationsHill stationHouseboat StayCru...,1
1,Charismatic Kochi Tour Package,4 Days & 3 Nights,Kochi (1D)Munnar (3D),9% Off,"â¹ 15,000/-â¹ 16,484/-",WaterfallsAdventureNatureShoppingWildlifeCultu...,1
2,Hills & Houseboat: Munnar and Alleppey Honeymo...,6 Days & 5 Nights,Munnar (2D)Thekkady (1D)Alleppey (1D)Kochi (2D),10% Off,"â¹ 22,000/-â¹ 24,444/-",Periyar Wildlife SanctuaryCruisesEravikulam Na...,1
3,Vibrant Kochi Munnar Honeymoon Tour Package,4 Days & 3 Nights,Cochin (1D)Munnar (3D),10% Off,"â¹ 14,571/-â¹ 16,190/-",Scenic viewsAdventureTea gardensHill stationMa...,1
4,Mesmerizing Getaway To Kochi,2 Days & 1 Nights,Kochi (2D),9% Off,"â¹ 4,800/-â¹ 5,275/-",ScenerylandscapeSightseeingLeisure TimeNatureA...,1
...,...,...,...,...,...,...,...
1215,Ecstatic Athirapally Tour Package,8 Days & 7 Nights,Athirapally (2D)Munnar (2D)Alleppey (1D)Kovala...,9% Off,"â¹ 28,123/-â¹ 30,904/-",Athirapally waterfallsNatureMunnarHill station...,61
1216,Mesmerizing Kerala Holiday: Weekend in Munnar ...,4 Days & 3 Nights,Munnar (2D)Thekkady (2D),29% Off,"â¹ 13,167/-â¹ 18,434/-",HillsAdventureJungle SafariNatureWildlifeWeeke...,61
1217,Captivating Thekkady Honeymoon Package,5 Days & 4 Nights,Kumarakom (1D)Thekkady (1D)Munnar (3D),10% Off,"â¹ 15,624/-â¹ 17,360/-",Ideal for CouplesWater ActivitiesAdventureHous...,61
1218,A Surreal Escape To Mesmerising Destinations,4 Days & 3 Nights,Munnar (2D)Alleppey (2D),21% Off,"â¹ 12,880/-â¹ 16,269/-",RomanticHill stationHillsCruisesWaterfallsAdve...,61
1219,Visit Kerala And See Astounding Places,4 Days & 3 Nights,Munnar (1D)Thekkady (1D)Kochi (2D),11% Off,"â¹ 11,760/-â¹ 13,213/-",Natural BeautyTea GardenSpice GardenSightseein...,61